python fenice_all.py \
  --input_file ../data/aggre_fact_xsum_sota_maverick.json \
  --result_file ../results/aggre_xsum_coref/fenice_wr0_wb1_wcc1_wc1_wm0_ww1_k1_ORCA.json \
  --weight_rouge 0.0 \
  --weight_bertscore 1.0 \
  --weight_compare_cont 1.0 \
  --weight_cont 1.0 \
  --weight_min 0.0 \
  --weight_mean 1.0 \
  --num_of_top_k 1 \
  --cuda_device 1 \

  python fenice_all.py \
  --input_file ../data/aggre_fact_cnndm_sota_maverick.json \
  --result_file ../results/aggre_cnndm_coref/fenice_wr0_wb1_wcc1_wc1_wm0_ww1_k1_ORCA.json \
  --weight_rouge 0.0 \
  --weight_bertscore 1.0 \
  --weight_compare_cont 1.0 \
  --weight_cont 1.0 \
  --weight_min 0.0 \
  --weight_mean 1.0 \
  --num_of_top_k 1 \
  --cuda_device 1 \
